### ISSUE TITLE
App crashes after integrating latest Android SDK

### ISSUE THREAD

**Issue by kirankmr450** [kontaktio/kontakt-android-sdk#34]
Hi There!
I have integrated latest Android SDK with my app and followed the steps outline in the documentation. I have also obtained my API Key. But for some reason my app crashes while initialising proximity manager (Crash log below). I am initialising proximity manager in a service which is started by my bluetooth broadcast receiver. The crash happens to be in ProximityManager connect function in onServiceConnected callback. I am not sure, what I am doing wrong. Really appreciate your quick help.
Best, Neeraj

8-13 00:06:30.783    5535-5535/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.xxxxxx.android.xxxxx:beaconservice, PID: 5535
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.kontakt.sdk.android.common.interfaces.SDKSupplier
            at com.kontakt.sdk.android.ble.manager.ProximityManager$1.onServiceConnected(ProximityManager.java:114)
            at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1203)
            at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1220)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by kirankmr450** [comment]
This is resolved now. This happens only when you make your service run in a separate process.

**Comment by ahasbini** [comment]
Hi,

I'm facing an issue with importing the Android SDK v2.0 into eclipse, I've referenced them by adding JARs first and it caused a `java.lang.NoClassDefFoundError`. Then I placed the libraries inside the /libs folder and added to build path, however it still ended up in error. It occurs on initializing the the Application.

``` java
public class TestApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        KontaktSDK.initialize(AppConstants.KONTAKT_API_KEY)
        .setDebugLoggingEnabled(BuildConfig.DEBUG)
        .setLogLevelEnabled(LogLevel.DEBUG, true)
        .setCrashlyticsLoggingEnabled(true);
    }

}
```

Here's the logcat:

```
10-08 21:52:52.952: E/AndroidRuntime(30217): java.lang.NoClassDefFoundError: com.kontakt.sdk.android.common.KontaktSDK
10-08 21:52:52.952: E/AndroidRuntime(30217):    at com.ahmadhasbini.beaconapp.TestApp.onCreate(TestApp.java:15)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4466)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at android.os.Handler.dispatchMessage(Handler.java:102)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at android.os.Looper.loop(Looper.java:136)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at android.app.ActivityThread.main(ActivityThread.java:5139)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at java.lang.reflect.Method.invokeNative(Native Method)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at java.lang.reflect.Method.invoke(Method.java:515)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
10-08 21:52:52.952: E/AndroidRuntime(30217):    at dalvik.system.NativeStart.main(Native Method)
```

Would appreciate your assistance on this, thanks in advance,

Ahmad Hasbini

**Comment by jakubkontakt** [comment]
Have you added all jar to your project? 

You need all jars to make it run.

**Comment by ahasbini** [comment]
Hello,

Yes I have added all jars into the project, but still having the same problem. Here's my .classpath file.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" path="src"/>
    <classpathentry kind="src" path="gen"/>
    <classpathentry exported="true" kind="lib" path="../../../Android-SDK/2.0.0/kontakt.io-android-sdk_2.0.0.jar">
        <attributes>
            <attribute name="javadoc_location" value="http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc//"/>
        </attributes>
    </classpathentry>
    <classpathentry exported="true" kind="lib" path="../../../Android-SDK/2.0.0/kontakt.io-api-client_2.0.0.jar">
        <attributes>
            <attribute name="javadoc_location" value="http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc//"/>
        </attributes>
    </classpathentry>
    <classpathentry exported="true" kind="lib" path="../../../Android-SDK/2.0.0/kontakt.io-ble-sdk_2.0.0.jar">
        <attributes>
            <attribute name="javadoc_location" value="http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc//"/>
        </attributes>
    </classpathentry>
    <classpathentry exported="true" kind="lib" path="../../../Android-SDK/2.0.0/kontakt.io-common-sdk_2.0.0.jar">
        <attributes>
            <attribute name="javadoc_location" value="http://kontaktio.github.io/Android-SDK/2.0.0/Javadoc//"/>
        </attributes>
    </classpathentry>
    <classpathentry kind="con" path="com.android.ide.eclipse.adt.ANDROID_FRAMEWORK"/>
    <classpathentry exported="true" kind="lib" path="libs/android-support-v4.jar" sourcepath="$ANDROID_HOME/extras/android/support/v4/src"/>
    <classpathentry exported="true" kind="con" path="com.android.ide.eclipse.adt.LIBRARIES"/>
    <classpathentry exported="true" kind="con" path="com.android.ide.eclipse.adt.DEPENDENCIES"/>
    <classpathentry kind="output" path="bin/classes"/>
</classpath>
```

In my previous comment, the Java compiler compliance was 1.6. I tried setting it to 1.7 however I still got the same error along with more errors.

```
10-11 22:13:33.086: E/AndroidRuntime(2400): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kontakt/sdk/android/common/KontaktSDK;
10-11 22:13:33.086: E/AndroidRuntime(2400):     at com.ahmadhasbini.beaconapp.TestApp.onCreate(TestApp.java:15)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at android.os.Looper.loop(Looper.java:135)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at android.app.ActivityThread.main(ActivityThread.java:5257)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at java.lang.reflect.Method.invoke(Native Method)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at java.lang.reflect.Method.invoke(Method.java:372)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
10-11 22:13:33.086: E/AndroidRuntime(2400): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kontakt.sdk.android.common.KontaktSDK" on path: DexPathList[[zip file "/data/app/com.ahmadhasbini.beaconapp-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-11 22:13:33.086: E/AndroidRuntime(2400):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-11 22:13:33.086: E/AndroidRuntime(2400):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-11 22:13:33.086: E/AndroidRuntime(2400):     ... 12 more
10-11 22:13:33.086: E/AndroidRuntime(2400):     Suppressed: java.lang.ClassNotFoundException: com.kontakt.sdk.android.common.KontaktSDK
10-11 22:13:33.086: E/AndroidRuntime(2400):         at java.lang.Class.classForName(Native Method)
10-11 22:13:33.086: E/AndroidRuntime(2400):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-11 22:13:33.086: E/AndroidRuntime(2400):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-11 22:13:33.086: E/AndroidRuntime(2400):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-11 22:13:33.086: E/AndroidRuntime(2400):         ... 13 more
10-11 22:13:33.086: E/AndroidRuntime(2400):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by patricktyll** [comment]
Solution:
Rename all the kontakt .jar Files in .zip and open the archive.
Now you can delete the duplicate Manifest file in the archive.
Rename it back to .jar and import the .jars into your project again.

JAR files are fundamentally archive files, built on the ZIP file format and have the .jar file extension.

If you export a library in eclipse you can uncheck the manifest file.
Kontakt-team forgot that.

**Comment by palettodiferro** [comment]
I modified your jar files deleting androidManifest.xml for each one. But I get another error now. I added this part of code to my main activity:

public class MainActivity extends Activity implements TabListener {

```
   public void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);         

        KontaktSDK.initialize(this)
        .setDebugLoggingEnabled(BuildConfig.DEBUG)
        .setLogLevelEnabled(LogLevel.DEBUG, true)
        .setCrashlyticsLoggingEnabled(true);
```

...........
..........
          }
}

When I run my activity I get the following errors:

11-12 18:05:34.501: E/AndroidRuntime(25500): FATAL EXCEPTION: main
11-12 18:05:34.501: E/AndroidRuntime(25500): java.lang.RuntimeException: Unable to start activity ComponentInfo{walkrecognizer.com.acc/walkrecognizer.com.acc.MainActivity}: java.lang.NullPointerException
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2071)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.ActivityThread.access$600(ActivityThread.java:138)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.os.Handler.dispatchMessage(Handler.java:99)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.os.Looper.loop(Looper.java:213)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.ActivityThread.main(ActivityThread.java:4787)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at java.lang.reflect.Method.invokeNative(Native Method)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at java.lang.reflect.Method.invoke(Method.java:511)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at dalvik.system.NativeStart.main(Native Method)
11-12 18:05:34.501: E/AndroidRuntime(25500): Caused by: java.lang.NullPointerException
11-12 18:05:34.501: E/AndroidRuntime(25500):    at com.kontakt.sdk.android.common.KontaktSDK.initialize(KontaktSDK.java:40)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at walkrecognizer.com.acc.MainActivity.onCreate(MainActivity.java:34)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.Activity.performCreate(Activity.java:5008)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
11-12 18:05:34.501: E/AndroidRuntime(25500):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2035)
11-12 18:05:34.501: E/AndroidRuntime(25500):    ... 11 more

I'm using Eclipse

**Comment by patricktyll** [comment]
I'm using Eclipse too.
Have you declared your API key + Activity inside the manifest?

Heres is my Code + Comments (Only the important one):

Manifest:
<application>
           
           <meta-data
            android:name="kontakt.io.API_KEY"
            android:value="MY_API_KEY_FROM_KONTAKT" />  
</application

public class AppClass extends Application{
       @Override
    public void onCreate() {
        super.onCreate();
               // I do this inside outside of an ancitivty. 
              //Maybe you change "this" to -->> this.getApplicationContext()
              // In my case "this" works fine
        KontaktSDK.initialize(this).setDebugLoggingEnabled(BuildConfig.DEBUG);

```
         //Secod version to initialize KontaktSDK
        KontaktSDK.initialize("API_KEY_AS_A_STRING");            
}
```

}

**Comment by noxius** [comment]
patricktyll can you put the libs without the manifest online please?

**Comment by jakubkontakt** [comment]
Hi, we fixed problem with jar integration. Our latest jars are single files and do not have AndroidManifest.xml file inside. Please test them and create new issue if something is still broken.

**Comment by naveen6768** [comment]
**_can someone help me out?, app is getting crashed on my kitkat os 4.4.2 physical device but running perfectly on emulator_**

✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
E/AndroidRuntime(25636): FATAL EXCEPTION: main
E/AndroidRuntime(25636): Process: com.example.angrybaazcustomer, PID: 25636
E/AndroidRuntime(25636): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.example.angrybaazcustomer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.angrybaazcustomer-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(25636): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5023)
E/AndroidRuntime(25636): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
E/AndroidRuntime(25636): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
E/AndroidRuntime(25636): 	at android.app.ActivityThread.access$1600(ActivityThread.java:151)
E/AndroidRuntime(25636): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
E/AndroidRuntime(25636): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(25636): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(25636): 	at android.app.ActivityThread.main(ActivityThread.java:5304)
E/AndroidRuntime(25636): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25636): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(25636): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
E/AndroidRuntime(25636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
E/AndroidRuntime(25636): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(25636): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.example.angrybaazcustomer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.angrybaazcustomer-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(25636): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(25636): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(25636): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(25636): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5008)
E/AndroidRuntime(25636): 	... 12 more
E/AndroidRuntime(25687): FATAL EXCEPTION: main
E/AndroidRuntime(25687): Process: com.example.angrybaazcustomer, PID: 25687
E/AndroidRuntime(25687): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.example.angrybaazcustomer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.angrybaazcustomer-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(25687): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5023)
E/AndroidRuntime(25687): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
E/AndroidRuntime(25687): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
E/AndroidRuntime(25687): 	at android.app.ActivityThread.access$1600(ActivityThread.java:151)
E/AndroidRuntime(25687): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
E/AndroidRuntime(25687): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(25687): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(25687): 	at android.app.ActivityThread.main(ActivityThread.java:5304)
E/AndroidRuntime(25687): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25687): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(25687): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
E/AndroidRuntime(25687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
E/AndroidRuntime(25687): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(25687): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.example.angrybaazcustomer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.angrybaazcustomer-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(25687): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(25687): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(25687): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(25687): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5008)
E/AndroidRuntime(25687): 	... 12 more
